### ISSUE TITLE
[Request for feature] More alert sounds to choose

### ISSUE THREAD

**Issue by gfoligna** [PagerDuty/chrome-notifier#15]
I would like the extension to have a few sounds to choose for notifications.
I've been looking at some in [here](https://freesound.org/search/?g=1&q=incident&f=%20license:%22Creative+Commons+0%22). If you approve I could select some to get a variety of sounds.

**Comment by richadams** [comment]
Hi @gfoligna,

We purposefully kept a single notification sound, as we didn't want the extension to end up being a collection of sounds that would take up most of the extension size.

If you'd like to use different sounds, the best path would be to download the code and change the sound file. You can then manually install the extension using any file that you like.

Thanks!
