### ISSUE TITLE
[General question/Idea] Firefox add-on port or website notifications

### ISSUE THREAD

**Issue by dehahost** [PagerDuty/chrome-notifier#20]
Hi.
I have a question for you developers: Will you also make a port of this add-on to Firefox's add-on library and/or make a option to turn on the notifications on PagerDuty website (i.e. like Facebook have)?

**Comment by richadams** [comment]
Hi @dehahost,

We currently have no plans to port this to Firefox. However one of the reasons for open-sourcing it was to allow others to modify or port it as they see fit. So if anyone is willing to port it, they're more than welcome to do so under the license terms, and are welcome to freely distribute it.

As for a feature on the PagerDuty product itself, the best path forward there is to reach out the PagerDuty Support Team (support@pagerduty.com), who will be able to put in an official feature request for this.

Thanks!
