### ISSUE TITLE
Notification on escalation of incident?

### ISSUE THREAD

**Issue by n0guest** [PagerDuty/chrome-notifier#6]
Hello.

Is there any way to show notification on escalation of incident? May be i missed something in settings.

PS: Thanks for very useful extension.

**Comment by richadams** [comment]
Hi,

There's no current way for the extension to show escalation of an incident, as it only looks for new incidents. But it should be possible to implement such a feature. 

I'll try to add such a feature for the next release. In the meantime, I'll keep this issue open to remind me.

Thanks!

**Comment by n0guest** [comment]
> I'll try to add such a feature for the next release. In the meantime, I'll keep this issue open to remind me.

It would be great to have such feature. Thank you.

**Comment by n0guest** [comment]
Hello. 

Is there any changes in your plans?

**Comment by richadams** [comment]
Sorry, this had completely slipped my mind! I took a look at the PagerDuty API this morning to see if there's a way I could implement this, unfortunately it doesn't look like there's any easy way to tell if an incident has escalated or not. The only way I can think of doing it is to keep track of each incident a notification has been shown for, and poll the API for any changes to the owner of the incident while making sure to exclude ones that are resolved. It would be a very hacky implementation and I'm not convinced it would work well.

If you have any ideas for a way to make this work, or if the API changes in future to expose a way for me to see if an incident has escalated, I'll definitely be open to including the feature. But unfortunately for now, I'm going to close this issue as "Can't Do" :(

Sorry I couldn't be more helpful.
