### ISSUE TITLE
Spaces in Notification Filters

### ISSUE THREAD

**Issue by alexismosquera** [PagerDuty/chrome-notifier#9]
Hi.
Congratulations for this extension!.  I'm having problems when I try to filter by Services. My company got the services names with spaces and now when I save the options these spaces disappear and the filter no longer works.  Would you please fix it?.  Would you please allow the spaces in the Filter Users and Filter Services fields?.

Many thanks!.

Regards,

Alexis Mosquera

**Comment by richadams** [comment]
Hi @alexismosquera,

It sounds like you're entering the name of the service into the field, but it should be the ID of the service instead (looks like `PIJ90N7`). This is why spaces are disallowed, as it will cause the API request to fail in the background.

If you have multiple services, you can separate with a `,`. e.g. `PIJ90N7,PF786D8,PE6Y35`, etc.

To find the ID of the service, go to it's page on the PagerDuty website and it will be in the URL, `https://<yourdomain>.pagerduty.com/services/<service_id>`, it starts with a `P` and will be about 7 characters long.

Cheers,
Rich

**Comment by alexismosquera** [comment]
Thank you very much! I will follow your suggestions.
